spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarySystemDb
      
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/,
        http://localhost:8764/eureka/
