spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: librarySystemDb
  zipkin:
    base-url: http://localhost:9411/
sleuth:
  sampler:
    probability: 1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8763/eureka/,
        http://localhost:8764/eureka/
